name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_increase:
        description: "Increase Version Number By"
        required: true
        default: "prerelease"
        type: choice
        options:
        - "prerelease"
        - "patch"
        - "minor"
        - "major"

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      # Set up environment
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable Poetry
        run: pipx install poetry
      # Increase Version
      - name: Increase Version
        id: increase-version
        run: |
          poetry version ${{ inputs.version_increase }}
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
      # Create and merge PR to increase version in main
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: gh-action/bump-version
          title: bump version ${{ inputs.version_increase }} to ${{ steps.increase-version.outputs.version }}
          delete-branch: true
          commit-message: bump version to ${{ steps.increase-version.outputs.version }}
