name: Release New Version

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tox.yml
  build_docs:
    uses: ./.github/workflows/docs_pages.yml
  release:
    name: Release
    needs: [test, build_docs]
    runs-on: ubuntu-latest
    steps:
      # Set up environment
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable Poetry
        uses: abatilo/actions-poetry@v2
      # Pull to refresh and build
      - name: Build Project
        run: poetry build
      # Actually release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increase-version.outputs.version }}
          draft: false
          generateReleaseNotes: true
          prerelease: ${{ steps.check-version.outputs.prerelease }}
        # -------------------------------------------------------------
        # if you want to test on test-pipy use these commands instead
        # poetry config repositories.test-pypi https://test.pypi.org/legacy/
        # poetry config pypi-token.test-pypi ${{ secrets.TESTPYPI_TOKEN }}
        # poetry publish -r test-pypi
        # -------------------------------------------------------------
      - name: Publish to PyPI
        if: steps.check-version.outputs.prerelease == 'false'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
      # merge main to dev to have up-to-date version number there
      - name: Merge main to dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: dev
          message: merge main to dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
